FROM openjdk:11-jdk
LABEL branched_from="2.5.19.06.20"

#RUN groupadd -g 1000 jenkins &&\
#    useradd -c "Jenkins user" -d /home/jenkins -u 1000 -g 1000 -m jenkins &&\
#    echo 'jenkins ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

#COPY --chown=jenkins ssh/* /home/jenkins/.ssh/
#COPY ssl/* /usr/local/share/ca-certificates/
#
#RUN chmod 755 /home/jenkins/.ssh/ &&\
#    chmod 700 /home/jenkins/.ssh/id_rsa &&\
#    chmod 644 /home/jenkins/.ssh/config &&\
#    chmod 644 /home/jenkins/.ssh/authorized_keys &&\
#    update-ca-certificates

RUN apt-get -y -q update &&\
    apt-get install -y --no-install-recommends git curl zip unzip &&\
    apt-get install -y --no-install-recommends python3 python3-dev python3-setuptools python3-pip build-essential libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev &&\
    apt-get install -y --no-install-recommends libffi-dev atool lsb-base lsb-release graphviz sshpass

RUN apt-get -q -y autoremove && apt-get -q clean -y && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin
RUN ln -nsf /usr/bin/python3 /usr/bin/python &&\
    ln -nsf /usr/bin/pip3 /usr/bin/pip

RUN pip install --upgrade setuptools wheel &&\
    pip install requests &&\
    pip install gitpython cryptography argparse chardet \
        colorama decorator ecdsa gitdb pycrypto html5lib networkx \
        paramiko pyparsing pydotplus pyvmomi urllib3 ssh-import-id \
        markupsafe pywinrm requests-credssp pymysql pytest pydot
RUN pip install ansible==2.9.9

#ENV PATH="${PATH}:/home/jenkins/.local/bin"
#USER jenkins

RUN pip install selenium &&\
    pip install robotframework robotframework-sshlibrary robotframework-selenium2library robotframework-debuglibrary robotframework-databaselibrary requests robotframework-requests robotframework-appiumlibrary &&\
    pip install zeep
